# Generated by Django 4.0.2 on 2022-07-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_c_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='c_for',
            field=models.CharField(blank=True, choices=[('woman', 'Woman'), ('man', 'Man')], max_length=200, null=True),
        ),
    ]
