# Generated by Django 4.0.3 on 2022-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_shopowner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
