# Generated by Django 4.0.3 on 2022-08-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem_rate_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
