# Generated by Django 4.0.3 on 2022-08-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_advance_order_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ManyToManyField(to='store.shopowner'),
        ),
    ]
