# Generated by Django 4.0.3 on 2022-08-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_order_shop_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='advance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='due',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
