# Generated by Django 4.0.3 on 2022-08-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orderitem_advance_orderitem_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='taken_user',
        ),
    ]
